version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
  parameter-store:
    AWS_ACCESS_KEY_ID: AccessKey
    AWS_SECRET_ACCESS_KEY: SecretKey
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - ./gradlew build
      - ./gradlew integ
