/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package software.amazon.awssdk.services.cloudwatchlogs.emf;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
